#ifndef PEAR_TESTS_CONFIG_HPP
#define PEAR_TESTS_CONFIG_HPP

#define PEAR_TEST_ADD_FILE
#define PEAR_TEST_ADD_SAME_NAMES
#define PEAR_TEST_ADD_DIRECTORY
#define PEAR_TEST_LOG

#define PEAR_TEST_NET_UPDATE
#define PEAR_TEST_NET_PULL
#define PEAR_TEST_CLEANUP
#define PEAR_TEST_CLEANUP_DRY_RUN

#endif // PEAR_TESTS_CONFIG_HPP
